---
version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/app/Dockerfile
      target: local
    ports:
      - ${DOCKER_COMPOSE_PORT_APP}:80
    volumes:
      - ./app:/var/www:cached
      - ./app/var/cache:/var/www/cache:delegated
    working_dir: /var/www
    environment:
      - ENVIRONMENT=local
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=erprof
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=32767
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST}

volumes:
  db-data:
